### ISSUE TITLE
Update "What's in the Beta" link for public beta

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#125]
Move the content of https://docs.google.com/document/d/1B82UpB191M-09cgor0rZuszueCoHswIeue3A822vcIg/edit into a static page, and change the link for "What's in the beta" in the header to point to this new page.

**Comment by jonearley** [comment]
Added this content as a static page. I did make a few edits:

- Edited content that was asking the user to look in a direction. That's an accessibility issue. It's better to direct by region or avoid giving navigation directions in websites.
- Renamed from "What's in the Beta" to "Feature Road Map" since that matches the document name. It's better to keep a link somewhere consistent with the location heading. Makes it so the user knows they landed in the right place.

**Comment by jonearley** [comment]
https://search-staging.www.lib.umich.edu/feature-road-map

Preview:

![screenshot-localhost-3000 2017-10-19 14-12-54-737](https://user-images.githubusercontent.com/1678665/31786797-ae178670-b4d7-11e7-82c3-aadab680c305.png)

**Comment by jonearley** [comment]
I just noticed those quotes on the what's to come heading shouldn't be there. I'll fix that.

**Comment by varnum** [comment]
Thanks for fixing the odd quotes — the page looks good.
