### ISSUE TITLE
Website Results -- People

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#60]
We also had People results specified in some detail, as a possible standalone datastore. Should the specified content of the preview & medium views be merged into the website results, so different kinds of content behave differently? Pinging @heidisb & @bnhowell .

Here's the spec text:

**Preview View**
_Fields_
- Name
- Working Title
- Email address

_User can_
- See contact email for people
- Access more information about people

**Medium View**
_Fields_
- Name
- Profile picture
- Working Title
- Department
- Email address
- Phone number
- Office

_User can_
- See all contact information for people
- Access more information about people
- Access Full View record
- Select and export records
- Email to user

 **Full View**
- People results do not have full views; the full view is the profile page.

**Comment by heidisb** [comment]
I think these reqs were from when we were thinking of this more as a staff directory replacement, which I've encouraged us to err away from since I'm doing some broader investigative work on our two directories/profiles situation. 

Just like for Research Guides, there are slightly different field needs here. Right now it's only showing the name and the Type. My instinct is:

Preview
- Name
- Type: Staff Directory/People
- Working Title
- Email 

Medium
- Name
- Type: Staff Directory/People
- Working Title
- Department
- Email 
- Phone

But I'm not sure how consistent this is with designs @Treevore has done for "smart" people results (i.e. for subject specialists).

**Comment by jonearley** [comment]
I'm not sure what is the final version is to implement here.

**Comment by varnum** [comment]
@heidisb @bnhowell Can we finalize these field specs so Jon can implement? I give them my thumbs up.

**Comment by heidisb** [comment]
I got designs from Trevor and he included both the profile picture and office on his medium view records (attached). If it's possible to do the profile picture, it definitely looks nice. I'm torn on whether we need office, but think including it is fine.  Note the Departments being shown in the mock-up are *not* the correct data (those are the Associations). 

Let's go with the original specs, plus Type: Staff Directory/People, as long as all that data is available to Jon. It'll give a solid snapshot of each person within the results. 

![library website 5c](https://user-images.githubusercontent.com/11546416/30167653-141b00a8-93b5-11e7-9fc2-f92aee21056f.png)

**Comment by bertrama** [comment]
Added as SEARCH-47.
