### ISSUE TITLE
As an advanced user, I want to see all filter value options, so that I can scope my search to what is available.

### ISSUE THREAD

**Issue by jonearley** [mlibrary/search#65]
**Context**
Pride only sends 20 of the top filter values to the advanced search filters. This should be updated and as close to comprehensive as possible (with consideration of performance when requesting all these).

**Tasks**
- [ ] Updated Pride to send as close to a comprehensive list of filters as possible when using `Pride.AllDatastores.get('[datastoure-uid]').get('facets')`.

**Questions**
- If a facet list has a really long tail of relevancy, what is the cut off limit? 200 filters?
- Does the limit have an impact on speed and performance (UX)? How do we decide?

**Success criteria**
When Pride sends nearly all filter value options.

**Comment by jonearley** [comment]
Removed `read to implement` tag until questions are addressed.

**Comment by varnum** [comment]
Because catalog records are updated in the index nightly, any newly-appearing fields wouldn't be in the data set until the nightly load. Could a nightly process generate static lists to display in search? I think a user would expect the language they want to be in the list, especially if there are relatively few items in it.

**For Mirlyn**
- There are about 220 academic disclipline entries
- There are about 450 language options
- There are about 45 format options
- There are about 170 place of publication options

**For Summon**
What are we doing in current ArticlesPlus? The list of languages and formats on https://www.lib.umich.edu/articlesplus/advanced is sufficient for new search, I think.

**Comment by bertrama** [comment]
Articles Plus gets the first page of facets the top 100.

These are loaded once at the startup of the application server.  I'm disinclined to build an extra process around maintaining static lists, or implementing an inflight update before the final launch.

**Comment by varnum** [comment]
I'm fine with Articles being capped at the top 100.

I'm a little less OK with Catalog not having the whole universe of possible languages, academic disciplines, formats, and places of publication -- feels like a reduction of functionality from current Mirlyn.

**Comment by bertrama** [comment]
To be clear, I'm only planning to cap ArticlesPlus at 100 unless solr has its own limit being imposed that I can't work around.
