### ISSUE TITLE
As a donor, I want to see acknowledgement that a catalog item was purchased with funds I provided

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#89]
Donor bookplates are viewed as essential -- and for online-only items, are required by the gift agreement -- by Development staff. 

Current Mirlyn records for items provided by donor funds display a "digital bookplate". E.g., https://mirlyn.lib.umich.edu/Record/005867744/

The code for a gift fund is stored in the 975 MARC field. There's a lookup table in ?????? to convert fund codes to displayable names. 

Examples in current Mirlyn:
https://mirlyn.lib.umich.edu/Record/005867744
https://mirlyn.lib.umich.edu/Record/004341068

**Comment by varnum** [comment]
Asked Tim P. where the lookup table is. Will update issue when I find out.

**Comment by bertrama** [comment]
No need to check with Tim.  Bookplate metadata has been available to the front end for a fairly long time.

**Comment by jonearley** [comment]
Since the field is available to me it was straightforward to add in like other existing fields.

Example (same as screenshow below): https://earleyj-drupal8.www.lib.umich.edu/catalog/record/005867744

![screenshot-earleyj-drupal8 www lib umich edu 2017-09-13 11-04-49](https://user-images.githubusercontent.com/1678665/30384837-67dd9242-9873-11e7-9ba4-134beba35c46.png)

**Comment by jonearley** [comment]
I sort of jumped ahead without designs, but this was easy to add. Maybe we can open a new ticket if we want to treat it differently and call this one closed for now?

**Comment by varnum** [comment]
I suspect @Treevore or @bnhowell may have some thoughts on design (and may already have designs done), but I'm good to call the basic issue closed. I'll create a new one to improve presentation.
